/**
 * Canonical list of translatable UI strings for the citizen app. This is the
 * exact set sent to POST /api/citizen/ui-translations. Keep in sync with the
 * t("...") calls in App.tsx — each entry is the English source AND the lookup
 * key (default-language-as-key i18n).
 */
export const UI_STRINGS: string[] = [
  "Your voice reaches your MP",
  "Logout",
  "What is the problem?",
  "Report a local issue in seconds through the protected LokSetu intake.",
  "How to get 100% reward",
  "Take a photo",
  "Speak",
  "Type",
  "Pothole, garbage, broken tap",
  "Record in any language",
  "Write the problem",
  "Prefer WhatsApp? Send us a message",
  "Your name stays private. AI removes personal details before your MP sees it.",
  "My reward total",
  "Show my reward total",
  "See cumulative reward points, milestone reached, and pending reports.",
  "No processed rewards yet. Submitted reports appear here after AI batch scoring.",
  "Track receipt",
  "Search",
  "Status",
  "Area",
  "Back",
  "100% reward guide",
  "Language",
  "Auto-detect language",
  "Photo of the problem",
  "Tap to open camera",
  "or choose from gallery",
  "Retake / choose another",
  "Record your voice",
  "Tap to stop",
  "Record again",
  "Tap to speak",
  "Listening…",
  "Hindi, Tamil, Bangla, Marathi, English — any language",
  "Listen once before submitting. Record again if needed.",
  "Describe the problem",
  "E.g. School toilets are broken and classrooms flood after rain.",
  "Add a note (optional)",
  "Anything to add",
  "Auto-detected area",
  "Location required",
  "Enable",
  "Sending to your MP…",
  "Submit problem",
  "Allow location to submit",
  "Submitted. Thank you!",
  "AI batch",
  "Reward pending",
  "Receipt ID",
  "Aadhaar",
  "format checked",
  "Search this receipt",
  "Report another problem",
  "+ More languages",
  "Choose your language",
  "Close",
  "Select a language",
  "Pick any Indian language. Your voice or text can still be in any language — this sets your preference.",
  "Auto-detect",
  "Detect from what you write or say",
  "Local",
  "Reward guide",
  "How to report well and earn 100% reward",
  "Cumulative reward",
  "points till date",
  "Current milestone",
  "Next milestone",
  "Top milestone reached",
  "Aadhaar access uses 12-digit format check only.",
  "Aadhaar number",
  "Continue",
  "Check cumulative reward",
  "Enter a 12-digit Aadhaar number."
];
