fullnameOverride: kube-prometheus-stack

alertmanager:
  enabled: true

grafana:
  enabled: true
  adminUser: admin
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password
  service:
    type: ClusterIP
    annotations:
      cloud.google.com/neg: '{"exposed_ports":{"80":{"name":"loksetu-observability-grafana-80"}}}'
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
    datasources:
      enabled: true
  additionalDataSources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: http://loki:3100
      isDefault: false
    - name: Tempo
      uid: tempo
      type: tempo
      access: proxy
      url: http://tempo:3100
      isDefault: false
      jsonData:
        tracesToLogsV2:
          datasourceUid: loki
        serviceMap:
          datasourceUid: prometheus
        nodeGraph:
          enabled: true
  grafana.ini:
    auth.anonymous:
      enabled: false

prometheus:
  prometheusSpec:
    retention: 7d
    scrapeInterval: 30s
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

prometheusOperator:
  admissionWebhooks:
    patch:
      enabled: false
