apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loksetu-platform-local
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shivam2003-dev/LokSetu.git
    targetRevision: main
    path: charts/people-priority
    helm:
      valueFiles:
        - values-local.yaml
        - values-local-platform.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: people-priority
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loksetu-web-local
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shivam2003-dev/LokSetu.git
    targetRevision: main
    path: charts/people-priority
    helm:
      valueFiles:
        - values-local.yaml
        - values-local-web.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: people-priority
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apni-awaaz-local
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shivam2003-dev/LokSetu.git
    targetRevision: main
    path: charts/people-priority
    helm:
      valueFiles:
        - values-local.yaml
        - values-local-apni-awaaz.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: people-priority
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
