{{- if .Values.components.api }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "people-priority.name" . }}-api
  labels:
    {{- include "people-priority.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.api.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "people-priority.name" . }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
{{- end }}
