{{- if .Values.components.citizen }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "people-priority.name" . }}-citizen
  labels:
    {{- include "people-priority.labels" . | nindent 4 }}
    app.kubernetes.io/component: citizen
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "people-priority.name" . }}
    app.kubernetes.io/component: citizen
  ports:
    - name: http
      port: {{ .Values.citizen.service.port }}
      targetPort: {{ .Values.citizen.service.targetPort }}
{{- end }}
