{{- if and .Values.components.ingress .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "people-priority.name" . }}
  labels:
    {{- include "people-priority.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "people-priority.name" . }}-web
                port:
                  number: {{ .Values.web.service.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "people-priority.name" . }}-api
                port:
                  number: {{ .Values.api.service.port }}
    - host: {{ .Values.ingress.citizenHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "people-priority.name" . }}-citizen
                port:
                  number: {{ .Values.citizen.service.port }}
{{- end }}
