{{- if .Values.components.web }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "people-priority.name" . }}-web
  labels:
    {{- include "people-priority.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "people-priority.name" . }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
{{- end }}
